### ISSUE TITLE
Can't write text in the forms right panel

### ISSUE THREAD

**Issue by apdex** [websiddu/sketch-material#14] opened 2017-07-18 15:07 UTC
After bringing the "Forms" I wasn't able to write anything in the right panel to change labels, placeholder text, or anything at all. 
I am using Sketch 45 with your plug-in latest version

**Comment by skycaptsteve** [comment] 2017-07-18 15:19
+1 Just downloaded, latest version of sketch. 

(otherwise great plugin, love the implementation it's so easy to use. Keep it up)

**Comment by websiddu** [comment] 2017-07-18 16:58
What version of Mac OS are you using. Generally it happen if you have an older version of Mac OS installed on your machine. 

Can you open https://sketch-material.firebaseapp.com/forms this in safari and tell me if you were able to change labels?

**Comment by skycaptsteve** [comment] 2017-07-18 18:24
Thanks for the reply.

I'm using 10.11.3 - Opened in safari, could not change labels. I'll try and
update the OS and report back.

**Comment by skycaptsteve** [comment] 2017-07-18 21:01
Updated MacOS 10.12.5, currently able to input text however nothing appears
when i click generate

**Comment by websiddu** [comment] 2017-07-18 21:55
What version of sketch you are using?  And also just try re-installing the plugin by downloading the latest version.

**Comment by websiddu** [comment] 2017-07-19 03:08
duplicate of #7

**Closed as completed by websiddu** 2017-07-19 03:08 UTC
