### ISSUE TITLE
A bug found in Toasts & Snackbars Generator

### ISSUE THREAD

**Issue by luyuan59** [websiddu/sketch-material#19] opened 2017-07-20 09:59 UTC
![bug in snackbar](https://user-images.githubusercontent.com/3895510/28411872-d496a66e-6d74-11e7-9166-1d54c249b401.gif)
As shown above.

Texting in button area is in the contrary order.

**Comment by websiddu** [comment] 2017-07-20 15:30
duplicate of #5

**Closed as completed by websiddu** 2017-07-20 15:30 UTC
