### ISSUE TITLE
Sketch 43.2 bugs: Chips, Snackbars, Forms, Tooltips

### ISSUE THREAD

**Issue by ameliacwong** [websiddu/sketch-material#21] opened 2017-07-20 14:20 UTC
Chips, Snackbars, Forms, and Tooltips are currently not working when using Sketch 43.2. Tried to regenerate all 4 multiple times, but nothing is coming up.

**Comment by websiddu** [comment] 2017-07-20 15:33
Sorry this plugin only works with sketch 45 and above. 

duplicate of #7

**Closed as completed by websiddu** 2017-07-20 15:33 UTC
