### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by elizabethnair** [websiddu/sketch-material#9] opened 2017-07-18 10:10 UTC
Creating any button caused my sketch to crash. 
Also, I couldn't click any of the fields under forms. Clicking that area just changed the form type. 

Great concept and great work! Thanks so much (:

**Comment by websiddu** [comment] 2017-07-18 14:13
Do you mind letting me know the version of Mac OS are you using?

**Comment by websiddu** [comment] 2017-07-19 03:06
duplicate of #7

**Closed as completed by websiddu** 2017-07-19 03:06 UTC
Labels: duplicate

**Comment by elizabethnair** [comment] 2017-07-24 12:43
Hi sorry! This went into a sub google folder. I am running on 10.10.5

**Comment by websiddu** [comment] 2017-07-24 17:56
Please try updating to 10.12.5
