### ISSUE TITLE
Does not work completely in the latest Sketch update (52.1)

### ISSUE THREAD

**Issue by kartoziya** [websiddu/sketch-material#73] opened 2018-10-06 10:07 UTC
Plugin does not work completely in the latest Sketch update (52.1).

**Comment by andypopa** [comment] 2018-10-08 20:54
Confirmed

**Comment by ghost** [comment] 2018-10-12 10:58
Hello. The icons do not place as symbols. Even with the latest update.

**Comment by ImperialBebek** [comment] 2018-10-15 04:38
Duplicate of : https://github.com/websiddu/sketch-material/issues/72

**Comment by websiddu** [comment] 2018-10-28 21:40
Refer to this thread #77

**Closed as completed by websiddu** 2018-10-28 21:40 UTC
